## Download movielens

In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
ml_path = "/home/caio/dev/recmodels/recmodels/data/ml-1m/ml_1m.pkl"

In [3]:
ml = pd.read_pickle(ml_path)

In [4]:
ml

,item,genres,user,rating,timestamp,binarized_rating
0,1,"[animation, children's, comedy]",1,5,978824268,1
1,1,"[animation, children's, comedy]",6,4,978237008,1
2,1,"[animation, children's, comedy]",8,4,978233496,1
3,1,"[animation, children's, comedy]",9,5,978225952,1
4,1,"[animation, children's, comedy]",10,5,978226474,1
...,...,...,...,...,...,...
1000204,3952,"[drama, thriller]",5812,4,992072099,1
1000205,3952,"[drama, thriller]",5831,3,986223125,0
1000206,3952,"[drama, thriller]",5837,4,1011902656,1
1000207,3952,"[drama, thriller]",5927,1,979852537,0
1000208,3952,"[drama, thriller]",5998,4,1001781044,1

In [5]:
from recmodels.knn.uknn import Uknn

In [6]:
ml

,item,genres,user,rating,timestamp,binarized_rating
0,1,"[animation, children's, comedy]",1,5,978824268,1
1,1,"[animation, children's, comedy]",6,4,978237008,1
2,1,"[animation, children's, comedy]",8,4,978233496,1
3,1,"[animation, children's, comedy]",9,5,978225952,1
4,1,"[animation, children's, comedy]",10,5,978226474,1
...,...,...,...,...,...,...
1000204,3952,"[drama, thriller]",5812,4,992072099,1
1000205,3952,"[drama, thriller]",5831,3,986223125,0
1000206,3952,"[drama, thriller]",5837,4,1011902656,1
1000207,3952,"[drama, thriller]",5927,1,979852537,0
1000208,3952,"[drama, thriller]",5998,4,1001781044,1

In [7]:
new_df = ml.copy()
new_df.loc[:, "user"] = ml["user"].astype("category").cat.codes
new_df.loc[:, "item"] = ml["item"].astype("category").cat.codes

In [8]:
new_df

,item,genres,user,rating,timestamp,binarized_rating
0,0,"[animation, children's, comedy]",0,5,978824268,1
1,0,"[animation, children's, comedy]",4,4,978237008,1
2,0,"[animation, children's, comedy]",6,4,978233496,1
3,0,"[animation, children's, comedy]",7,5,978225952,1
4,0,"[animation, children's, comedy]",8,5,978226474,1
...,...,...,...,...,...,...
1000204,3700,"[drama, thriller]",5080,4,992072099,1
1000205,3700,"[drama, thriller]",5096,3,986223125,0
1000206,3700,"[drama, thriller]",5102,4,1011902656,1
1000207,3700,"[drama, thriller]",5183,1,979852537,0
1000208,3700,"[drama, thriller]",5250,4,1001781044,1

In [9]:
model = Uknn(ml)

In [10]:
torch.tensor(ml["user"].unique())

tensor([   1,    6,    8,  ..., 3298,  768, 5727])

In [11]:
users = torch.tensor(new_df["user"].unique())
items = torch.tensor(new_df["item"].unique())

In [12]:
model.fit(ml)

In [13]:
model.recommend(users=users, candidates=items, k=20)

(tensor([[  18,   10,    4,  ...,    2,    6,   14],
         [  18,   10,    4,  ...,    2,    6,   14],
         [1088, 1307, 1947,  ...,  912,  919, 2243],
         ...,
         [2858, 2997,  223,  ..., 1617, 3253,  318],
         [1246,  296,  527,  ..., 2858, 2000, 1196],
         [ 480, 2571, 1580,  ..., 1917,  329, 2393]]),
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.9044, 0.8854, 0.8091,  ..., 0.4967, 0.4061, 0.4056],
         ...,
         [1.0000, 1.0000, 0.9039,  ..., 0.7898, 0.7878, 0.7837],
         [0.9086, 0.9086, 0.9035,  ..., 0.7222, 0.7208, 0.7198],
         [0.9077, 0.9043, 0.9030,  ..., 0.6113, 0.5323, 0.5298]]))